[package]
name = "rust_chess_engine"
version = "0.1.0"
edition = "2021"
authors = ["Samuel Henderson"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pleco = "0.5.0"